"""Self-test fixture for build_reel.py: synthetic 16:9 clips plus the config files around them.

  python make_reel_fixture.py --out <dir>
  python build_reel.py --config <dir>/reel.json --draft       # must print PASS
  python build_reel.py --config <dir>/reel.json                # must print PASS

Writes <dir>/clips/*.mp4 (6 synthetic 1920x1080 clips, testsrc2 + a sine tone, encoded like a real
proxy), <dir>/bed.m4a (a 40 s sine bed, unused by the fixture's own reel.json but there for a
manual audio-mode "bed" try), <dir>/cuts.json (12 shots ~1.6 s each, mixed x_offset - some
centred, some shifted), <dir>/fonts (fetched via dji-vlog-series's fetch_fonts.py), and
<dir>/reel.json (silent audio mode, sans+mono lockup, serif omitted). Nothing here touches a real
project.
"""
import argparse, json, subprocess, sys
from pathlib import Path

AP = argparse.ArgumentParser()
AP.add_argument("--out", required=True, help="fixture directory (created)")
AP.add_argument("--fps", type=int, default=25)
A = AP.parse_args()

OUT = Path(A.out).resolve()
CLIPS = OUT / "clips"
CLIPS.mkdir(parents=True, exist_ok=True)

W, H = 1920, 1080
# stem, seconds, hue shift (so each clip reads differently), tone Hz
CLIP_DEFS = [
    ("fix_a", 9.0, 0, 220), ("fix_b", 8.0, 60, 262), ("fix_c", 10.0, 120, 294),
    ("fix_d", 8.5, 180, 330), ("fix_e", 9.5, 240, 392), ("fix_f", 8.0, 300, 440),
]


def run(args):
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode:
        sys.exit(r.stderr[-2000:])


for stem, secs, hue, hz in CLIP_DEFS:
    dst = CLIPS / f"{stem}.mp4"
    if dst.exists():
        continue
    run(["ffmpeg", "-hide_banner", "-y",
         "-f", "lavfi", "-t", str(secs), "-i", f"testsrc2=size={W}x{H}:rate={A.fps}",
         "-f", "lavfi", "-t", str(secs), "-i", f"sine=frequency={hz}:sample_rate=48000",
         "-vf", f"hue=h={hue},drawbox=0:0:{W}:120:color=black@0.6:t=fill",
         "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-g", str(A.fps),
         "-keyint_min", str(A.fps), "-bf", "0", "-pix_fmt", "yuv420p",
         "-c:a", "aac", "-b:a", "128k", "-ac", "2", "-shortest", str(dst)])
    print("clip", dst.name)

bed = OUT / "bed.m4a"
if not bed.exists():
    run(["ffmpeg", "-hide_banner", "-y", "-f", "lavfi", "-t", "40",
         "-i", "sine=frequency=110:sample_rate=48000", "-ac", "2", "-c:a", "aac", "-b:a", "128k",
         str(bed)])
    print("bed", bed.name)

# 12 shots across the 6 clips, ~1.6s each, mixed x_offset (None = centred).
OFFSETS = [None, 300, None, -300, 500, None, -500, 200, None, -200, 400, None]
shots = []
for i in range(12):
    stem, secs, _, _ = CLIP_DEFS[i % len(CLIP_DEFS)]
    in_t = 0.4 if i < len(CLIP_DEFS) else secs - 2.2   # two non-overlapping windows per clip
    shot = {"file": f"{stem}.mp4", "in": round(in_t, 2), "out": round(in_t + 1.6, 2)}
    if OFFSETS[i] is not None:
        shot["x_offset"] = OFFSETS[i]
    shots.append(shot)
json.dump({"shots": shots}, open(OUT / "cuts.json", "w"), indent=1)

fonts = OUT / "fonts"
fetch_fonts = Path(__file__).resolve().parent.parent.parent / "dji-vlog-series" / "scripts" / "fetch_fonts.py"
if not fetch_fonts.exists():
    sys.exit(f"dji-vlog-series/scripts/fetch_fonts.py not found at {fetch_fonts}")
subprocess.run([sys.executable, str(fetch_fonts), "--out", str(fonts)], check=True)

json.dump({
    "_readme": "Generated by make_reel_fixture.py. "
               "python build_reel.py --config reel.json --draft",
    "proxies": "clips", "output": "out/fixture-reel.mp4",
    "canvas": [1080, 1920], "fps": A.fps, "cuts": "cuts.json",
    "lockup": {
        "lines": [
            {"text": "FIXTURE REEL", "font": "sans", "size": 70, "tracking": 2},
            {"text": "A TEST OF THE GRID", "font": "mono", "size": 28, "tracking": 4},
        ],
        "position": "top", "top_px": 180, "color": "#FFFFFF", "shadow": [0, 2, 18, 0.5],
    },
    "audio": {"mode": "silent"},
    "design": {"fonts": {"sans": "fonts/Montserrat[wght].ttf", "mono": "fonts/IBMPlexMono-Regular.ttf"}},
}, open(OUT / "reel.json", "w"), indent=1)

print(f"fixture in {OUT}: {len(CLIP_DEFS)} clips, {len(shots)} shots, "
      f"{sum(s['out']-s['in'] for s in shots):.1f}s\n"
      f"next: python build_reel.py --config {OUT / 'reel.json'} --draft")
